"""globk_frame — GLOBK multi-station Helmert frame solution (blind spot 3, the heaviest).

Core scientific correction for real projects: after a GAMIT loosely constrained single-day
solution (each station weakly constrained at 5 cm), reading the o/q-file coordinates directly
lets the absolute height drift with the network shape -> the 38 mm bimodal distribution at DAEJ.
Adding the GLOBK frame realisation step (glred epoch-by-epoch + glorg multi-station Helmert
stabilisation) resolves it (operational project: DAEJ height std 13.9 -> 6.7 mm, bimodality gone).

Recipe ported from an operational GLOBK configuration (globk/glorg command files + run script).
Command files are parameterised (expt/apr/frame-site set/eq_file). Requires GAMIT h-files
(htoglb converts them to .glx).
"""
import os
import re
import subprocess
from pathlib import Path

GG = os.environ.get("GG_DIR", str(Path.home() / "gg"))
GLOBK_BIN = f"{GG}/kf/bin/globk"
HTOGLB_BIN = f"{GG}/kf/bin/htoglb"


GLOBK_CMD_TMPL = """* globk command file (auto-generated by gamit-agent globk_frame)
{eq_line}
 srt_file @.srt
 srt_dir +1
 apr_file {apr}
 max_chii 13 3 100
 org_cmd {glorg_cmd}
 crt_opt NOPR
 prt_opt NOPR GDLF
 org_opt PSUM GDLF FIXA RNRP
 apr_site all 10 10 10 0 0 0
 apr_wob  10 10 1 1
 apr_ut1  10 1
 apr_tran 1 1 1 0 0 0
 apr_svan all F F F
 del_scra yes
"""

GLORG_CMD_TMPL = """* glorg command file (auto-generated by gamit-agent globk_frame)
 apr_file {apr}
 pos_org xtran ytran ztran xrot yrot zrot
 stab_it 4 0.8 3.0
 cnd_hgt 10 10
 stab_site clear
 stab_site {frame_sites}
"""


def _env():
    env = dict(os.environ)
    for d in (f"{GG}/kf/bin", f"{GG}/com"):
        if d not in env.get("PATH", ""):
            env["PATH"] = d + ":" + env["PATH"]
    return env


def _find_hfiles(project_dir, expt):
    """Find GAMIT h-files (h<expt>a.<yr><doy>). Returns absolute paths (needed because subprocess cwd=gsoln)."""
    return sorted(str(p.resolve()) for p in Path(project_dir).rglob(f"h{expt}a.*")
                  if re.search(r"\.\d{5}$", p.name))


def htoglb_convert(gsoln, hfiles, env):
    """Convert GAMIT ASCII h-files into binary .glx and place them in gsoln. Returns the list of .glx."""
    glx = []
    for hf in hfiles:
        proc = subprocess.run([HTOGLB_BIN, gsoln, "tmp.svs", hf],
                              cwd=gsoln, env=env, capture_output=True, text=True)
        glx += [str(p) for p in Path(gsoln).glob("h*.glx")]
    return sorted(set(glx))


def parse_org_heights(org_path):
    """Parse the epoch-by-epoch station coordinate estimates in the .org file ->
    per-station ellipsoidal-height time series + std (mm).

    Capture estimate lines of the form 'N. SITE_GPS X coordinate (m)  <apriori> <adjust> <...>',
    accumulate the (X,Y,Z) triplets per station (one set per epoch), convert to ellipsoidal
    height, and compute the std. Statistically meaningful only for a multi-day solution.
    """
    import statistics
    from tools.stations import ecef_to_geodetic
    text = Path(org_path).read_text(errors="replace")
    pat = re.compile(r"\b([A-Z0-9]{4})_\w+\s+([XYZ]) coordinate\s+\(m\)\s+"
                     r"(-?[\d.]+)\s+(-?[\d.]+)")
    acc = {}   # stn -> {"X":[], "Y":[], "Z":[]}
    for m in pat.finditer(text):
        stn, comp, apriori, adjust = m.group(1), m.group(2), float(m.group(3)), float(m.group(4))
        acc.setdefault(stn, {"X": [], "Y": [], "Z": []})[comp].append(apriori + adjust)
    out = {}
    for stn, d in acc.items():
        n = min(len(d["X"]), len(d["Y"]), len(d["Z"]))
        if n == 0:
            continue
        heights = []
        for i in range(n):
            _, _, h = ecef_to_geodetic(d["X"][i], d["Y"][i], d["Z"][i])
            heights.append(h)
        out[stn] = {"n": n,
                    "mean_h_m": round(statistics.mean(heights), 4),
                    "std_u_mm": round(statistics.pstdev(heights) * 1000, 2) if n > 1 else 0.0}
    return out


def globk_frame(project_dir, expt, frame_sites=None, apr_rel="tables/lfile.",
                eq_file=None, run=True):
    """Generate the command files + (optionally) actually run the GLOBK frame solution.
    Returns {gsoln, n_hfiles, org, heights}.

    frame_sites: the stabilisation site set (list of 4-character codes); when None, use all
    stations (cases such as excluding DAEJ for an independent check are controlled by the caller).
    run=False only generates the command files (handy for inspection/testing).
    """
    proj = Path(project_dir).resolve()
    gsoln = proj / "gsoln"
    gsoln.mkdir(exist_ok=True)
    if not expt:
        return {"error": "expt is required"}

    hfiles = _find_hfiles(project_dir, expt)
    apr = (proj / apr_rel)
    apr_arg = str(apr) if apr.is_file() else "lfile."

    frame_sites = frame_sites or []
    fs = " ".join(f"{s.upper()}_GPS" for s in frame_sites) or "all"
    eq_line = f" eq_file {eq_file}" if eq_file else "*"

    (gsoln / "globk_auto.cmd").write_text(GLOBK_CMD_TMPL.format(
        eq_line=eq_line, apr=apr_arg, glorg_cmd="glorg_auto.cmd"))
    (gsoln / "glorg_auto.cmd").write_text(GLORG_CMD_TMPL.format(
        apr=apr_arg, frame_sites=fs))

    result = {"gsoln": str(gsoln), "n_hfiles": len(hfiles),
              "cmd_files": ["gsoln/globk_auto.cmd", "gsoln/glorg_auto.cmd"]}
    if not hfiles:
        result["warning"] = (f"no h{expt}a.<yr><doy> h-file found in the project; "
                             "GLOBK needs GAMIT h-files (produced by the single-day solution). Command files generated, awaiting a run.")
        return result
    if not run:
        return result

    env = _env()
    glx = htoglb_convert(str(gsoln), hfiles, env)
    if not glx:
        result["error"] = "htoglb produced no .glx; cannot continue"
        return result
    # write the gdl + run globk epoch by epoch (glred style)
    gdl = gsoln / "auto.gdl"
    gdl.write_text("\n".join(f" {Path(g).name} 0 0" for g in glx) + "\n")
    org = gsoln / "auto.org"
    for f in (gsoln / "auto.prt", gsoln / "auto.log", org):
        if f.exists():
            f.unlink()
    n = 0
    for g in glx:
        L = gsoln / f"L_{Path(g).stem}"
        L.write_text(Path(g).name + "\n")
        subprocess.run([GLOBK_BIN, "6", "auto.prt", "auto.log", L.name, "globk_auto.cmd"],
                       cwd=str(gsoln), env=env, capture_output=True, text=True)
        L.unlink(missing_ok=True)
        n += 1
    result["n_epochs"] = n
    result["org"] = str(org)
    if org.is_file():
        result["heights"] = parse_org_heights(org)
    return result
